package: fontconfig

essential:
  - fontconfig_copyright

slices:
  bins:
    essential:
      - fontconfig_cache
      - fontconfig-config_config
      - libc6_libs
      - libfontconfig1_libs
      - libfreetype6_libs
    contents:
      /usr/bin/fc-cache:
      /usr/bin/fc-cat:
      /usr/bin/fc-conflist:
      /usr/bin/fc-list:
      /usr/bin/fc-match:
      /usr/bin/fc-pattern:
      /usr/bin/fc-query:
      /usr/bin/fc-scan:
      /usr/bin/fc-validate:

  cache:
    contents:
      # The postinst script runs fc-cache to regenerate
      # the fonts cache and populate that directory
      /var/cache/fontconfig/: {make: true}

  copyright:
    contents:
      /usr/share/doc/fontconfig/copyright:
