package: libsensors-config
# hello world

essential:
  - libsensors-config_copyright

slices:
  config:
    contents:
      /etc/sensors.d/:
      /etc/sensors3.conf:

  copyright:
    contents:
      /usr/share/doc/libsensors-config/copyright:
