package: netplan-generator

essential:
  - netplan-generator_copyright

slices:
  libs:
    essential:
      - libc6_libs
      - libglib2.0-0t64_libs
      - libnetplan1_libs
      - libuuid1_libs
      - systemd_services
    contents:
      /usr/lib/netplan/PLACEHOLDER:
      /usr/lib/systemd/system-generators/netplan:
      /usr/libexec/netplan/generate:

  copyright:
    contents:
      /usr/share/doc/netplan-generator/copyright:
