name: Test chisel-releases CI

on:
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/*.yaml"
      - ".github/scripts/validate-hints/**"

jobs:
  test-validate-hints:
    name: Test validate hints workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          pip-install: -r .github/scripts/validate-hints/requirements.txt
      - run: pip install pytest
      - name: Run "validate-hints" unit tests
        run: |
          pytest .github/scripts/validate-hints/

  # TODO: add tests for remaining CI scripts
